import type { ObraWithConstrutora } from "@/types/obra"

export const FORNECEDORES_SANTA_BARBARA: ObraWithConstrutora[] = [
  {
    id: "mock-sb-grupo-7",
    nome: "Grupo 7 - Obras & Engenharia Civil",
    slug: "grupo-7-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-grupo-7",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3200,
    unidades_disponiveis: 12,
    descricao_curta: "Construção de casas de alto padrão no Santa Bárbara Resort Residence com gestão completa de obra.",
    descricao_longa: "O Grupo 7 é especialista em projetos residenciais e gestão de obras no condomínio Santa Bárbara Resort Residence. Com foco na qualidade construtiva, cumprimento rigoroso de prazos e excelência no acabamento, garantimos que seu imóvel seja construído com máxima segurança e valorização patrimonial.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Alvenaria", "Fundações", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-grupo-7",
      nome: "Grupo 7",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/6944094e-dd24-4c88-9203-3d4aac1e09ff/697ba011-be8c-43c7-ac5a-7203ac1e09ff.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5514997465968",
      telefone: "(14) 99746-5968",
      email: "contato@grupo7.eng.br",
      responsavel: "Diretoria Técnica Grupo 7",
      cidadeAtendimento: "Santa Bárbara Resort Residence e Região",
    },
    reviews: [
      {
        id: "rev-sb-grupo-7-1",
        author: "Proprietário Verificado",
        role: "Morador - Santa Bárbara Resort",
        content: "Excelente atendimento e condução da obra. Transparência em cada etapa e acabamento impecável.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-sb-ea3-engenharia",
    nome: "EA3 Engenharia & Construções",
    slug: "ea3-engenharia-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-ea3",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3400,
    unidades_disponiveis: 14,
    descricao_curta: "Engenharia civil de precisão, projetos arquitetônicos e construção residencial completa no resort.",
    descricao_longa: "A EA3 Engenharia atua no desenvolvimento de projetos e execução de obras de alto padrão, combinando planejamento detalhado, controle de custos e tecnologias modernas para residências no Santa Bárbara Resort Residence.",
    cover_image_url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Fundações", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-ea3",
      nome: "EA3 Engenharia",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/61c332d0-6074-4cc1-8b8e-59bfac1e09ff/698f2efd-ad1c-47c3-b9be-23ffac1e09ff.png",
    },
    supplier_rating: {
      score: 4.8,
      count: 4,
    },
    contato: {
      whatsapp: "5514981050090",
      telefone: "(14) 98105-0090 / (11) 91273-1736",
      email: "contato@ea3engenharia.com.br",
      responsavel: "Eng. Responsável EA3",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
    reviews: [
      {
        id: "rev-sb-ea3-1",
        author: "Carlos P. Silveira",
        role: "Proprietário no Resort",
        content: "Engenheiros muito capacitados. Cumpriram o cronograma e entregaram a casa antes do previsto.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 3 semanas",
      },
    ],
  },
  {
    id: "mock-sb-lv-engeo",
    nome: "LV Engeo Engenharia e Arquitetura",
    slug: "lv-engeo-viviane-luan-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-lv-engeo",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3600,
    unidades_disponiveis: 18,
    descricao_curta: "Projetos arquitetônicos e construção completa com Viviane e Luan (CREA-SP 5070231028).",
    descricao_longa: "A LV Engeo Engenharia e Arquitetura, liderada pelos especialistas Viviane e Luan, possui destacada atuação no Santa Bárbara Resort Residence com avaliação máxima de clientes. Integramos projeto arquitetônico contemporâneo com rigor técnico de engenharia.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Alvenaria", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-lv-engeo",
      nome: "Viviane e Luan - LV Engeo",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/610c229d-bcac-403f-a1e2-4869ac1e09ff/69b42ea5-c128-4d09-8278-0b04ac1e09ff.jpeg",
    },
    supplier_rating: {
      score: 5.0,
      count: 18,
    },
    contato: {
      whatsapp: "5514998518142",
      telefone: "(14) 99851-8142",
      email: "contato@lvengeo.com.br",
      responsavel: "Viviane e Luan (CREA-SP 5070231028)",
      cidadeAtendimento: "Santa Bárbara Resort Residence e Região",
    },
    reviews: [
      {
        id: "rev-sb-lv-1",
        author: "Mariana Alcantara",
        role: "Proprietária Residencial",
        content: "A Viviane e o Luan são fantásticos! Cuidaram de cada detalhe da nossa casa desde a planta até a entrega final.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 2 semanas",
      },
    ],
  },
  {
    id: "mock-sb-andre-cobois",
    nome: "André Cobois Construções",
    slug: "andre-cobois-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-andre-cobois",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3100,
    unidades_disponiveis: 10,
    descricao_curta: "Construção civil especializada em residências de campo e lazer com alto padrão de execução.",
    descricao_longa: "André Cobois Construções oferece mão de obra especializada e administração de obras com experiência comprovada no Santa Bárbara Resort Residence. Qualidade estrutural e cumprimento de cronograma com pontualidade.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Reformas & Ampliações", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-andre-cobois",
      nome: "André Cobois Construções",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/6747628e-c874-4661-8cbe-72c8ac1e0fec/682e3fd5-2748-4539-9462-61a7ac1e0fec.png",
    },
    supplier_rating: {
      score: 4.8,
      count: 6,
    },
    contato: {
      whatsapp: "5514998650336",
      telefone: "(14) 99865-0336 / (14) 99675-8357",
      email: "contato@andrecobois.com.br",
      responsavel: "André Cobois",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-ojn-engenharia",
    nome: "OJN Engenharia e Construções",
    slug: "ojn-engenharia-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-ojn",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3300,
    unidades_disponiveis: 15,
    descricao_curta: "Engenharia e execução estrutural para casas de campo e lazer com garantia e solidez.",
    descricao_longa: "A OJN Engenharia e Construções entrega soluções construtivas completas com supervisão técnica contínua e equipe treinada para projetos arquitetônicos modernos no Santa Bárbara Resort Residence.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Fundações", "Alvenaria", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-ojn",
      nome: "OJN Engenharia e Construções",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/68dc22ae-0940-4410-8097-0348ac1e09ff/e245d5a1-1b7d-45d0-8489-5c06c5ac66fd.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 4,
    },
    contato: {
      whatsapp: "5511988154189",
      telefone: "(11) 98815-4189 / (11) 94898-4799",
      email: "contato@ojnengenharia.com.br",
      responsavel: "Engenharia OJN",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-omega-construtora",
    nome: "Ômega Construtora",
    slug: "omega-construtora-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-omega",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3500,
    unidades_disponiveis: 16,
    descricao_curta: "Construção de alto padrão, projetos modernos e acabamento diferenciado no Santa Bárbara Resort.",
    descricao_longa: "A Ômega Construtora é amplamente reconhecida no condomínio pela pontualidade, atendimento personalizado e alta qualidade construtiva, contando com mais de 14 avaliações 5 estrelas.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Alvenaria", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-omega",
      nome: "Ômega Construtora",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/6851c8e8-2bcc-40a6-8fb7-7e0eac1e09ff/68640262-3c34-4cef-8ce7-0f76ac1e0fec.jpeg",
    },
    supplier_rating: {
      score: 5.0,
      count: 14,
    },
    contato: {
      whatsapp: "5511993272598",
      telefone: "(11) 99327-2598 / (11) 96945-6178",
      email: "contato@omegaconstrutora.com.br",
      responsavel: "Equipe Ômega",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-rpr-construcoes",
    nome: "RPR Construções",
    slug: "rpr-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-rpr",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3250,
    unidades_disponiveis: 12,
    descricao_curta: "Qualidade, agilidade e confiança na construção da sua residência no resort.",
    descricao_longa: "A RPR Construções executa projetos completos no Santa Bárbara Resort Residence com foco em solidez estrutural, cumprimento das normas do condomínio e fidelidade ao projeto do cliente.",
    cover_image_url: "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-rpr",
      nome: "RPR Construções",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/65eb5c74-e340-4054-b876-1f1eac1e09ff/66ba143d-9c30-495d-ad36-6c59ac1e09ff.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 6,
    },
    contato: {
      whatsapp: "5514991063280",
      telefone: "(14) 99106-3280",
      email: "contato@rprconstrucoes.com.br",
      responsavel: "Diretoria RPR",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-audeir-construcoes",
    nome: "Audeir Construções",
    slug: "audeir-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-audeir",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3150,
    unidades_disponiveis: 10,
    descricao_curta: "Execução de obras residenciais completas, da fundação à entrega das chaves.",
    descricao_longa: "Audeir Construções atua no Santa Bárbara Resort Residence com dedicação em todas as etapas construtivas, garantindo segurança na estrutura e beleza nos acabamentos.",
    cover_image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Fundações", "Alvenaria", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-audeir",
      nome: "Audeir Construções",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/61b74074-d224-476c-9075-1e26ac1e09ff/66cde436-8e0c-478a-b373-2206ac1e09ff.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5511978713314",
      telefone: "(11) 97211-2466 / (11) 97871-3314",
      email: "contato@audeirconstrucoes.com.br",
      responsavel: "Audeir",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-was-construtora",
    nome: "WAS Construtora, Engenharia e Arquitetura",
    slug: "was-construtora-engenharia-arquitetura-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-was",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3550,
    unidades_disponiveis: 11,
    descricao_curta: "Soluções integradas de engenharia e arquitetura para residências de alto padrão.",
    descricao_longa: "A WAS Construtora une arquitetura sofisticada, cálculos de engenharia precisos e gestão completa para casas no Santa Bárbara Resort Residence.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Alvenaria", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-was",
      nome: "WAS Construtora, Engenharia e Arquitetura",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/675ae47d-4750-4033-b5b3-708fac1e09ff/678e5395-0c0c-44cf-8ec2-5d0fac1e09ff.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5511966484202",
      telefone: "(11) 96648-4202",
      email: "contato@wasconstrutora.com.br",
      responsavel: "Equipe WAS",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-mr-engenharia",
    nome: "MR Engenharia & Construtora",
    slug: "mr-engenharia-construtora-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-mr",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3450,
    unidades_disponiveis: 12,
    descricao_curta: "Projetos, cálculo estrutural e construção de qualidade no Santa Bárbara Resort.",
    descricao_longa: "A MR Engenharia & Construtora oferece suporte integral desde a aprovação de projetos na prefeitura e condomínio até a entrega das chaves da sua residência.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Fundações", "Alvenaria"],
    construtoras: {
      id: "construtora-sb-mr",
      nome: "MR Engenharia & Construtora",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/69bd7f16-5930-499b-a851-64a7ac1e09ff/ca1a3648-558a-4c53-a621-541bd796275a.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5511951383294",
      telefone: "(11) 95138-3294",
      email: "contato@mrengenharia.com.br",
      responsavel: "Engenharia MR",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-jlbc-engenharia",
    nome: "JLBC ENGENHARIA LTDA",
    slug: "jlbc-engenharia-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-jlbc",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3600,
    unidades_disponiveis: 10,
    descricao_curta: "Gestão executiva e engenharia de alto nível para residências contemporâneas.",
    descricao_longa: "A JLBC Engenharia atua com seriedade e eficiência, executando projetos residenciais no Santa Bárbara Resort Residence com gestão completa de insumos e mão de obra.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Gerenciamento", "Fundações"],
    construtoras: {
      id: "construtora-sb-jlbc",
      nome: "JLBC ENGENHARIA LTDA",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/68d44a39-2968-4e19-b38a-2e5cac1e0fec/905a0a8c-6c2e-4f3c-a252-7c52e9a43bac.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5531991959767",
      telefone: "(31) 99195-9767",
      email: "contato@jlbcengenharia.com.br",
      responsavel: "Diretoria JLBC",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-edvan-construcoes",
    nome: "Edvan Construções em Geral",
    slug: "edvan-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-edvan",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3000,
    unidades_disponiveis: 14,
    descricao_curta: "Mão de obra especializada e acompanhamento direto na construção civil residencial.",
    descricao_longa: "Edvan Construções em Geral proporciona segurança e economia na execução da sua residência no resort, com equipe experiente e dedicada a acabamentos finos.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-edvan",
      nome: "Edvan Construções em Geral",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/68d58141-e62c-4bce-ab3e-6d43ac1e09ff/68dab6b4-f298-4411-8dbf-7ef8ac1e0fec.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5511975818239",
      telefone: "(11) 97581-8239 / (11) 97645-2648",
      email: "contato@edvanconstrucoes.com.br",
      responsavel: "Edvan",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-construtora-tcc",
    nome: "Construtora TCC Multiserviços",
    slug: "construtora-tcc-multiservicos-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-tcc",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3100,
    unidades_disponiveis: 15,
    descricao_curta: "Construção completa, reformas e manutenções com equipes dedicadas e ágeis.",
    descricao_longa: "A Construtora TCC Multiserviços oferece soluções completas para proprietários no Santa Bárbara Resort Residence, desde construções novas até reformas estruturais e ampliações.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Reformas & Ampliações", "Instalações"],
    construtoras: {
      id: "construtora-sb-tcc",
      nome: "Construtora TCC Multiserviços",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/685ede08-60dc-4dac-98ed-2e36ac1e09ff/6863c96d-c23c-4d4f-adec-04a2ac1e09ff.png",
    },
    supplier_rating: {
      score: 5.0,
      count: 4,
    },
    contato: {
      whatsapp: "5519987723378",
      telefone: "(19) 98772-3378",
      email: "contato@tccmultiservicos.com.br",
      responsavel: "Equipe TCC",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-simperiofer",
    nome: "Construtora Simperiofer",
    slug: "construtora-simperiofer-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-simperiofer",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3350,
    unidades_disponiveis: 12,
    descricao_curta: "Especializada em fundações, estruturas de concreto e alvenaria de alta performance.",
    descricao_longa: "A Simperiofer alia engenharia rigorosa e materiais de qualidade superior para garantir durabilidade e conforto térmico e acústico em construções no resort.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Fundações", "Alvenaria", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-simperiofer",
      nome: "Construtora Simperiofer",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/67bf68ac-fbf8-49b7-aa62-3dd4ac1e09ff/67c2019e-9324-4859-b1f0-1a2bac1e09ff.jpeg",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5514991449094",
      telefone: "(14) 99144-9094",
      email: "contato@simperiofer.com.br",
      responsavel: "Diretoria Simperiofer",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-facilita-gestao",
    nome: "Facilita Gestão Construtiva",
    slug: "facilita-gestao-construtiva-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-facilita",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3650,
    unidades_disponiveis: 16,
    descricao_curta: "Gestão completa de obras, controle financeiro transparente e entrega com padrão superior.",
    descricao_longa: "A Facilita Gestão Construtiva traz ao Santa Bárbara Resort Residence um modelo de gerenciamento inteligente, fornecendo relatórios periódicos, otimização de compras e controle fino de acabamento.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Gerenciamento", "Projetos & Arquitetura", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-facilita",
      nome: "Facilita Gestão Construtiva",
      logo_url: "https://thumb-cdn.soluall.net/prod/adv_ads/ad300box/686c1793-2cf4-4208-9f0f-4205ac1e0fec/68920539-3248-4b2d-891e-75c7ac1e09ff.jpg",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5519997553258",
      telefone: "(19) 99755-3258 / (19) 99702-0650",
      email: "contato@facilitagestao.com.br",
      responsavel: "Gestão Facilita",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-jd-construcoes",
    nome: "JD Construções",
    slug: "jd-construcoes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-jd",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 2950,
    unidades_disponiveis: 8,
    descricao_curta: "Execução ágil de obras civis e reformas em geral no condomínio Santa Bárbara.",
    descricao_longa: "A JD Construções realiza serviços de fundação, alvenaria, reboco e reformas residenciais no Santa Bárbara Resort Residence com compromisso e responsabilidade técnica.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Reformas & Ampliações"],
    construtoras: {
      id: "construtora-sb-jd",
      nome: "JD Construções",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='36' font-family='Arial' font-weight='bold' text-anchor='middle'>JD</text></svg>",
    },
    supplier_rating: {
      score: 4.0,
      count: 1,
    },
    contato: {
      whatsapp: "5591992221820",
      telefone: "(91) 99222-1820",
      email: "contato@jdconstrucoes.com.br",
      responsavel: "Equipe JD",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-construtora-jr",
    nome: "Construtora JR",
    slug: "construtora-jr-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-jr",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3100,
    unidades_disponiveis: 11,
    descricao_curta: "Construção de casas térreas e sobrados com ótimo custo-benefício e fino acabamento.",
    descricao_longa: "A Construtora JR tem ampla vivência em obras residenciais unifamiliares, oferecendo transparência nos custos, controle de cronograma e acabamento primoroso.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-jr",
      nome: "Construtora JR",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='36' font-family='Arial' font-weight='bold' text-anchor='middle'>JR</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5514996203862",
      telefone: "(14) 99620-3862",
      email: "contato@construtorajr.com.br",
      responsavel: "Responsável JR",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-irmaos-gomes",
    nome: "Construtora Irmãos Gomes",
    slug: "construtora-irmaos-gomes-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-irmaos-gomes",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3200,
    unidades_disponiveis: 13,
    descricao_curta: "Tradição em construção civil residencial, fundação sólida e acabamentos de qualidade.",
    descricao_longa: "A Construtora Irmãos Gomes atende clientes no Santa Bárbara Resort Residence com experiência familiar e técnica, assegurando solidez em cada etapa da obra.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-irmaos-gomes",
      nome: "Construtora Irmãos Gomes",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='32' font-family='Arial' font-weight='bold' text-anchor='middle'>IG</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5514996441479",
      telefone: "(14) 99644-1479 / (14) 99707-6190",
      email: "contato@irmaosgomes.com.br",
      responsavel: "Irmãos Gomes",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-equipe-a",
    nome: "Construtora Equipe A",
    slug: "construtora-equipe-a-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-equipe-a",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3300,
    unidades_disponiveis: 10,
    descricao_curta: "Equipe especializada em alvenaria estrutural, projetos e gerenciamento com foco em prazos.",
    descricao_longa: "A Construtora Equipe A une planejamento, velocidade construtiva e rigor no atendimento aos padrões arquitetônicos exigidos pelo Santa Bárbara Resort.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Gerenciamento", "Projetos & Arquitetura"],
    construtoras: {
      id: "construtora-sb-equipe-a",
      nome: "Construtora Equipe A",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='32' font-family='Arial' font-weight='bold' text-anchor='middle'>EQ.A</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 1,
    },
    contato: {
      whatsapp: "5514997155328",
      telefone: "(14) 99715-5328",
      email: "contato@equipea.com.br",
      responsavel: "Coordenação Equipe A",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-avior-construtora",
    nome: "Avior Construtora",
    slug: "avior-construtora-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-avior",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3500,
    unidades_disponiveis: 14,
    descricao_curta: "Engenharia moderna e execução de residências com alto padrão estético e funcional.",
    descricao_longa: "A Avior Construtora executa residências unifamiliares de luxo no Santa Bárbara Resort Residence, prezando pela inovação de métodos construtivos e satisfação total.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Alvenaria", "Acabamento Fino"],
    construtoras: {
      id: "construtora-sb-avior",
      nome: "Avior Construtora",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='32' font-family='Arial' font-weight='bold' text-anchor='middle'>AVIOR</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 3,
    },
    contato: {
      whatsapp: "5511947335321",
      telefone: "(11) 94733-5321 / (11) 98897-2029",
      email: "contato@aviorconstrutora.com.br",
      responsavel: "Equipe Avior",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-ramon-r4",
    nome: "Ramon R4 Construtor",
    slug: "ramon-r4-construtor-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-ramon-r4",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3150,
    unidades_disponiveis: 10,
    descricao_curta: "Construção de casas no campo com foco em durabilidade, beleza e economia de recursos.",
    descricao_longa: "Ramon R4 Construtor traz dedicação presencial na obra, garantindo alinhamento perfeito com o proprietário e execução com zelo em cada detalhe construtivo.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Reformas & Ampliações"],
    construtoras: {
      id: "construtora-sb-ramon-r4",
      nome: "Ramon R4 Construtor",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='32' font-family='Arial' font-weight='bold' text-anchor='middle'>R4</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 2,
    },
    contato: {
      whatsapp: "5542998428419",
      telefone: "(42) 99842-8419",
      email: "contato@ramonr4.com.br",
      responsavel: "Ramon R4",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-mg-construcao",
    nome: "MG Construção",
    slug: "mg-construcao-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-mg",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 2900,
    unidades_disponiveis: 9,
    descricao_curta: "Serviços de construção, fundações e alvenaria para lotes no Santa Bárbara Resort.",
    descricao_longa: "A MG Construção realiza serviços civis gerais com equipe prática, atuando na infraestrutura básica, fundação e alvenaria de residências.",
    cover_image_url: "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Instalações"],
    construtoras: {
      id: "construtora-sb-mg",
      nome: "MG Construção",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='36' font-family='Arial' font-weight='bold' text-anchor='middle'>MG</text></svg>",
    },
    supplier_rating: {
      score: 4.0,
      count: 1,
    },
    contato: {
      whatsapp: "5511912059339",
      telefone: "(11) 91205-9339",
      email: "contato@mgconstrucao.com.br",
      responsavel: "Responsável MG",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
  },
  {
    id: "mock-sb-rodrigo-feitosa",
    nome: "Rodrigo Feitosa - Construtor",
    slug: "rodrigo-feitosa-construtor-santa-barbara",
    cidade: "Águas de Santa Bárbara",
    estado: "SP",
    bairro: "Santa Bárbara Resort Residence (Águas de Santa Bárbara)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-sb-rodrigo-feitosa",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 3200,
    unidades_disponiveis: 12,
    descricao_curta: "Experiência prática e excelência no acompanhamento e construção no Santa Bárbara Resort.",
    descricao_longa: "Rodrigo Feitosa é construtor com comprovada experiência no Santa Bárbara Resort Residence, reconhecido por clientes pela dedicação, honestidade e entrega pontual de casas de campo.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-sb-rodrigo-feitosa",
      nome: "Rodrigo Feitosa - Construtor",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><text x='50' y='60' fill='%23ea580c' font-size='36' font-family='Arial' font-weight='bold' text-anchor='middle'>RF</text></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 3,
    },
    contato: {
      whatsapp: "5514996532004",
      telefone: "(14) 99653-2004",
      email: "contato@rodrigofeitosa.com.br",
      responsavel: "Rodrigo Feitosa",
      cidadeAtendimento: "Santa Bárbara Resort Residence",
    },
    reviews: [
      {
        id: "rev-sb-rf-1",
        author: "Felipe N.",
        role: "Proprietário",
        content: "O Rodrigo conduziu nossa obra com maestria. Excelente profissional e de total confiança.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
]
