import type { ObraWithConstrutora } from "@/types/obra"
import { AREAS_OBRA } from "@/lib/areas-obra"

const FORNECEDORES_BASE: ObraWithConstrutora[] = [
  {
    id: "mock-1-mpd",
    nome: "Residência Horizon Alphaville",
    slug: "mpd-engenharia-alphaville",
    cidade: "Barueri",
    estado: "SP",
    bairro: "Alphaville (Barueri / Santana de Parnaíba)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-mpd",
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: 4800,
    unidades_disponiveis: 34,
    descricao_curta: "Mais de 40 anos de liderança em construção de residências de altíssimo padrão em Alphaville e Tamboré.",
    descricao_longa: "A MPD Engenharia é referência consolidada em obras de alto e altíssimo padrão nos condomínios Alphaville e Tamboré. Com mais de quatro décadas de história, oferecemos corpo técnico próprio, rigoroso cumprimento de cronogramas e transparência financeira em regime de administração ou preço fechado.\n\nEspecializada em fundações complexas, estrutura em concreto protendido, integração com projetos contemporâneos e acabamentos finos importados.",
    cover_image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Fundações", "Alvenaria", "Gerenciamento"],
    construtoras: {
      id: "construtora-mpd",
      nome: "MPD Engenharia",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%230f172a'/><path d='M25 75V25L50 50L75 25V75' stroke='%23ea580c' stroke-width='8' stroke-linecap='round' stroke-linejoin='round' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 48,
    },
    contato: {
      whatsapp: "5511998765432",
      telefone: "(11) 4197-8000",
      email: "contato@mpdengenharia.com.br",
      responsavel: "Eng. Ricardo Silveira",
      cidadeAtendimento: "Alphaville, Tamboré e Região",
    },
    reviews: [
      {
        id: "rev-1-mpd",
        author: "Carlos Eduardo Mendes",
        role: "Proprietário - Residencial Tamboré 2",
        content: "Entrega impecável com 15 dias de antecedência. O controle de qualidade e a prestação de contas semanal transmitiram segurança absoluta durante os 14 meses de obra.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 2 semanas",
      },
      {
        id: "rev-2-mpd",
        author: "Fernanda G. Vasconcelos",
        role: "Arquiteta Parceira",
        content: "Parceria de alto nível. Respeitam o detalhamento arquitetônico e resolvem interferências de canteiro com extrema competência de engenharia.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-2-cazzabella",
    nome: "Mansão Colina Fazenda Boa Vista",
    slug: "cazzabella-obras-fazenda-boa-vista",
    cidade: "Porto Feliz",
    estado: "SP",
    bairro: "Fazenda Boa Vista (Porto Feliz)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-cazzabella",
    is_published: true,
    created_at: "2024-03-02T10:00:00Z",
    updated_at: "2024-03-02T10:00:00Z",
    preco_a_partir: 5600,
    unidades_disponiveis: 22,
    descricao_curta: "Especializada em residências de campo contemporâneas, estruturas em balanço e paisagismo integrado.",
    descricao_longa: "A Cazzabella é a principal escolha de arquitetos de renome para construções no interior de São Paulo, especialmente na Fazenda Boa Vista, Boa Vista Village e Terras de São José.\n\nCom mão de obra altamente qualificada para ripados de madeira nobre, caixilharia minimalista e concreto aparente ripado, transformamos projetos arrojados em realidade.",
    cover_image_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-cazzabella",
      nome: "Cazzabella Obras & Design",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%2318181b'/><circle cx='50' cy='50' r='28' stroke='%23ea580c' stroke-width='6' fill='none'/><path d='M40 38L62 50L40 62Z' fill='%23ea580c'/></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 36,
    },
    contato: {
      whatsapp: "5511987654321",
      telefone: "(11) 3045-9200",
      email: "obras@cazzabella.com.br",
      responsavel: "Arq. Marcelo Cazzabella",
      cidadeAtendimento: "Fazenda Boa Vista, Itu e Porto Feliz",
    },
    reviews: [
      {
        id: "rev-1-caz",
        author: "Renato Diniz",
        role: "Proprietário - Fazenda Boa Vista",
        content: "Excelente acabamento. A integração de marcenaria de alto luxo e pedra moledo ficou impecável. Empresa pontual e séria.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 3 semanas",
      },
    ],
  },
  {
    id: "mock-3-diase",
    nome: "Villa Moderna Tamboré",
    slug: "diase-construtora-tambore",
    cidade: "Santana de Parnaíba",
    estado: "SP",
    bairro: "Tamboré (Barueri / Santana de Parnaíba)",
    categoria: "residencial",
    status: "pronto_para_morar",
    construtora_id: "construtora-diase",
    is_published: true,
    created_at: "2024-03-03T10:00:00Z",
    updated_at: "2024-03-03T10:00:00Z",
    preco_a_partir: 4200,
    unidades_disponiveis: 19,
    descricao_curta: "Engenharia de precisão com foco em sustentabilidade, conforto térmico e execução técnica limpa.",
    descricao_longa: "A Diase Construtora reúne vasta bagagem técnica em alvenaria estrutural reforçada, lajes nervuradas e automação predial residencial para residências nos residenciais Tamboré 1, 2, 3, 10 e 11.",
    cover_image_url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Fundações", "Alvenaria", "Instalações", "Acabamento Fino"],
    construtoras: {
      id: "construtora-diase",
      nome: "Diase Construtora",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><rect x='28' y='28' width='44' height='44' stroke='%23ea580c' stroke-width='6' fill='none'/><line x1='28' y1='28' x2='72' y2='72' stroke='%23ea580c' stroke-width='5'/></svg>",
    },
    supplier_rating: {
      score: 5.0,
      count: 42,
    },
    contato: {
      whatsapp: "5511976543210",
      telefone: "(11) 4688-2100",
      email: "contato@diase.com.br",
      responsavel: "Eng. Paulo Alcantara",
      cidadeAtendimento: "Santana de Parnaíba e Barueri",
    },
    reviews: [
      {
        id: "rev-1-dia",
        author: "Guilherme B.",
        role: "Proprietário - Tamboré 10",
        content: "Planejamento orçamentário transparente. Sem surpresas ou aditivos abusivos. Recomendo de olhos fechados.",
        rating: 5,
        ratings: { tempo_execucao: 4, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-4-steelcorp",
    nome: "Residência Bioclimática Swiss Park",
    slug: "steelcorp-light-steel-frame",
    cidade: "Campinas",
    estado: "SP",
    bairro: "Swiss Park (Campinas)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-steelcorp",
    is_published: true,
    created_at: "2024-03-04T10:00:00Z",
    updated_at: "2024-03-04T10:00:00Z",
    preco_a_partir: 2850,
    unidades_disponiveis: 15,
    descricao_curta: "Construção a seco industrializada em Light Steel Frame com entrega até 3x mais rápida.",
    descricao_longa: "A SteelCorp é pioneira em obras estruturadas em aço leve galvanizado (Light Steel Frame). Projetos executados com precisão milimétrica, isolamento termoacústico superior e obra 100% limpa com zero desperdício.",
    cover_image_url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Steel Frame", "Projetos & Arquitetura", "Instalações"],
    construtoras: {
      id: "construtora-steelcorp",
      nome: "SteelCorp Engenharia & Inovação",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%23334155'/><path d='M30 70V30L70 70V30' stroke='%23ffffff' stroke-width='7' stroke-linecap='round' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.8,
      count: 29,
    },
    contato: {
      whatsapp: "5519981234567",
      telefone: "(19) 3254-7700",
      email: "orcamentos@steelcorp.com.br",
      responsavel: "Eng. Lucas Prado",
      cidadeAtendimento: "Campinas, Valinhos e Vinhedo",
    },
    reviews: [
      {
        id: "rev-1-ste",
        author: "Juliana Camargo",
        role: "Proprietária - Swiss Park",
        content: "A rapidez da estrutura Steel Frame impressionou todos os vizinhos. Casa entregue em 7 meses com acabamento perfeito.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 2 meses",
      },
    ],
  },
  {
    id: "mock-5-monolitico",
    nome: "Casa Ecológica Granja Viana",
    slug: "monolitico-engenharia-eps",
    cidade: "Cotia",
    estado: "SP",
    bairro: "Granja Viana (Cotia)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-monolitico",
    is_published: true,
    created_at: "2024-03-05T10:00:00Z",
    updated_at: "2024-03-05T10:00:00Z",
    preco_a_partir: 2400,
    unidades_disponiveis: 12,
    descricao_curta: "Construção em Painéis Monolíticos de EPS com alta eficiência térmica e economia estrutural.",
    descricao_longa: "A Monolítico Engenharia entrega obras com o moderno sistema construtivo de painéis monolíticos de EPS com argamassa armada. Casas mais frescas no verão e aquecidas no inverno, com redução de até 30% no tempo de levantamento da alvenaria.",
    cover_image_url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Painel Monolítico (EPS)", "Alvenaria", "Instalações"],
    construtoras: {
      id: "construtora-monolitico",
      nome: "Monolítico EPS Construtora",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%230f172a'/><rect x='25' y='25' width='20' height='20' rx='4' fill='%23ea580c'/><rect x='55' y='25' width='20' height='20' rx='4' fill='%23ea580c'/><rect x='25' y='55' width='20' height='20' rx='4' fill='%23ea580c'/><rect x='55' y='55' width='20' height='20' rx='4' fill='%23ea580c'/></svg>",
    },
    supplier_rating: {
      score: 4.7,
      count: 23,
    },
    contato: {
      whatsapp: "5511982345678",
      telefone: "(11) 4702-8890",
      email: "contato@monoliticoeps.com.br",
      responsavel: "Eng. Rafael Fontes",
      cidadeAtendimento: "Granja Viana, Cotia e Jandira",
    },
    reviews: [
      {
        id: "rev-1-mon",
        author: "Márcio Toledo",
        role: "Contratante - Granja Viana",
        content: "O isolamento acústico e térmico da casa é surreal. Excelente equipe, muito organizados e pontuais.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 4, qualidade: 5, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-6-terraplan",
    nome: "Infraestrutura Terras de São José",
    slug: "terraplan-topografia-e-solo",
    cidade: "Itu",
    estado: "SP",
    bairro: "Terras de São José I e II (Itu)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-terraplan",
    is_published: true,
    created_at: "2024-03-06T10:00:00Z",
    updated_at: "2024-03-06T10:00:00Z",
    preco_a_partir: 1950,
    unidades_disponiveis: 40,
    descricao_curta: "Terraplenagem de precisão a laser, topografia planialtimétrica cadastral e fundações profundas.",
    descricao_longa: "Frota própria de escavadeiras, pás carregadeiras e rolos compactadores para grandes movimentações de terra em condomínios fechados. Serviços de contenção de encostas, muros de arrimo em gabião e estacas hélice contínua.",
    cover_image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Topografia", "Preparação do Solo", "Terraplenagem", "Fundações"],
    construtoras: {
      id: "construtora-terraplan",
      nome: "Terraplan Engenharia de Solo",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231c1917'/><path d='M20 70L40 40L60 60L80 30' stroke='%23ea580c' stroke-width='7' stroke-linecap='round' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.9,
      count: 31,
    },
    contato: {
      whatsapp: "5511993456789",
      telefone: "(11) 4022-3344",
      email: "comercial@terraplanengenharia.com.br",
      responsavel: "Eng. Otávio Bueno",
      cidadeAtendimento: "Itu, Indaiatuba e Porto Feliz",
    },
    reviews: [
      {
        id: "rev-1-ter",
        author: "Construtora Horizonte",
        role: "Parceiro Técnico",
        content: "Topografia entregue com nuvem de pontos impecável e terraplenagem perfeitamente nivelada no gabarito do projeto.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 3 semanas",
      },
    ],
  },
  {
    id: "mock-7-bernardes",
    nome: "Residência Alpha 2 Master",
    slug: "bernardes-engenharia-luxo",
    cidade: "Barueri",
    estado: "SP",
    bairro: "Alpha 2 (Barueri)",
    categoria: "residencial",
    status: "pronto_para_morar",
    construtora_id: "construtora-bernardes",
    is_published: true,
    created_at: "2024-03-07T10:00:00Z",
    updated_at: "2024-03-07T10:00:00Z",
    preco_a_partir: 6200,
    unidades_disponiveis: 8,
    descricao_curta: "Ateliê de engenharia e construção com acabamentos nobres, automação Lutron e pisos aquecidos.",
    descricao_longa: "Construímos residências exclusivas para clientes exigentes nos mais nobres residenciais de São Paulo e interior. Gestão total da obra através de plataforma digital com relatórios diários de obra (RDO).",
    cover_image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Acabamento Fino", "Gerenciamento"],
    construtoras: {
      id: "construtora-bernardes",
      nome: "Bernardes & Associados Engenharia",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%230f172a'/><path d='M30 30H55C66 30 66 50 55 50H30M55 50H60C72 50 72 70 60 70H30V30' stroke='%23ea580c' stroke-width='7' stroke-linecap='round' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.9,
      count: 44,
    },
    contato: {
      whatsapp: "5511974567890",
      telefone: "(11) 3168-5000",
      email: "projetos@bernardesengenharia.com.br",
      responsavel: "Engª. Beatriz Bernardes",
      cidadeAtendimento: "Alphaville, São Paulo e Campinas",
    },
    reviews: [
      {
        id: "rev-1-ber",
        author: "Felipe S. Prado",
        role: "Proprietário - Alpha 2",
        content: "A qualidade dos detalhes e o pós-obra foram os melhores que já experimentei. Vale cada centavo investido.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-8-paulista",
    nome: "Reforma Estrutural Parque dos Príncipes",
    slug: "paulista-obras-reformas",
    cidade: "São Paulo",
    estado: "SP",
    bairro: "Parque dos Príncipes (São Paulo)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-paulista",
    is_published: true,
    created_at: "2024-03-08T10:00:00Z",
    updated_at: "2024-03-08T10:00:00Z",
    preco_a_partir: 1450,
    unidades_disponiveis: 25,
    descricao_curta: "Especialistas em reformas completas, ampliações de residências e modernização de instalações.",
    descricao_longa: "Atuamos com reformas civis residenciais e comerciais, demolição controlada com laudos estruturais, reforço de vigas com perfis metálicos, substituição de telhados e repaginação completa de ambientes.",
    cover_image_url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Reformas & Ampliações", "Instalações", "Alvenaria"],
    construtoras: {
      id: "construtora-paulista",
      nome: "Paulista Obras & Reformas",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><path d='M30 70V40L50 25L70 40V70H30Z' stroke='%23ea580c' stroke-width='6' fill='none'/><path d='M45 70V50H55V70' stroke='%23ea580c' stroke-width='4' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.6,
      count: 19,
    },
    contato: {
      whatsapp: "5511965678901",
      telefone: "(11) 3781-4400",
      email: "contato@paulistaobras.com.br",
      responsavel: "Eng. André Martins",
      cidadeAtendimento: "São Paulo, Cotia e Osasco",
    },
    reviews: [
      {
        id: "rev-1-pau",
        author: "Claudio Nogueira",
        role: "Contratante - Parque dos Príncipes",
        content: "Excelente trabalho na reforma da nossa casa. Reforço de vigas e troca de telhado sem nenhuma infiltração. Preço justo.",
        rating: 5,
        ratings: { tempo_execucao: 4, experiencia: 5, qualidade: 5, preco: 5 },
        date: "Há 2 semanas",
      },
    ],
  },
  {
    id: "mock-9-helvetia",
    nome: "Vila Country Helvetia",
    slug: "helvetia-construcoes-indaiatuba",
    cidade: "Indaiatuba",
    estado: "SP",
    bairro: "Helvetia Country (Indaiatuba)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-helvetia",
    is_published: true,
    created_at: "2024-03-09T10:00:00Z",
    updated_at: "2024-03-09T10:00:00Z",
    preco_a_partir: 4900,
    unidades_disponiveis: 14,
    descricao_curta: "Casas de campo em estilo toscano e contemporâneo nos principais condomínios de Indaiatuba.",
    descricao_longa: "A Helvetia Construções alia tradição construtiva e moderna gestão de engenharia. Atendemos o Helvetia Country, Maison Du Parc e Dona Lucilla com projetos personalizados.",
    cover_image_url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Projetos & Arquitetura", "Fundações", "Acabamento Fino"],
    construtoras: {
      id: "construtora-helvetia",
      nome: "Helvetia Obras de Campo",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e1b4b'/><circle cx='50' cy='50' r='26' stroke='%23ea580c' stroke-width='6' fill='none'/><path d='M35 50H65M50 35V65' stroke='%23ea580c' stroke-width='6'/></svg>",
    },
    supplier_rating: {
      score: 4.8,
      count: 27,
    },
    contato: {
      whatsapp: "5519976789012",
      telefone: "(19) 3875-1200",
      email: "contato@helvetiaobras.com.br",
      responsavel: "Eng. Gustavo Meirelles",
      cidadeAtendimento: "Indaiatuba, Itu e Salto",
    },
    reviews: [
      {
        id: "rev-1-hel",
        author: "Patrícia Lemos",
        role: "Proprietária - Helvetia",
        content: "Acompanhamento impecável de toda a obra. Excelente equipe de acabamentos finos.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-10-apex",
    nome: "Edifício Comercial Saint Patrick",
    slug: "apex-engenharia-gestao",
    cidade: "Sorocaba",
    estado: "SP",
    bairro: "Saint Patrick (Sorocaba)",
    categoria: "comercial",
    status: "lancamento",
    construtora_id: "construtora-apex",
    is_published: true,
    created_at: "2024-03-10T10:00:00Z",
    updated_at: "2024-03-10T10:00:00Z",
    preco_a_partir: 2600,
    unidades_disponiveis: 16,
    descricao_curta: "Gerenciamento e execução de obras comerciais, clínicas e escritórios corporativos modernos.",
    descricao_longa: "A Apex Engenharia foca em obras comerciais ágeis com método BIM 5D para compatibilização de projetos hidráulicos, elétricos e de climatização.",
    cover_image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Gerenciamento", "Projetos & Arquitetura", "Instalações"],
    construtoras: {
      id: "construtora-apex",
      nome: "Apex Gestão de Obras",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%231e293b'/><path d='M25 70L50 25L75 70H60L50 48L40 70H25Z' fill='%23ea580c'/></svg>",
    },
    supplier_rating: {
      score: 4.7,
      count: 18,
    },
    contato: {
      whatsapp: "5515987890123",
      telefone: "(15) 3233-9000",
      email: "orcamentos@apexgestao.com.br",
      responsavel: "Eng. Fábio Arruda",
      cidadeAtendimento: "Sorocaba e Araçoiaba da Serra",
    },
    reviews: [
      {
        id: "rev-1-apx",
        author: "Dr. Marcos Vinicius",
        role: "Proprietário de Clínica",
        content: "Executaram nossa clínica em tempo recorde sem estouro de orçamento. Gestão nota 10.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 4, preco: 5 },
        date: "Há 3 semanas",
      },
    ],
  },
  {
    id: "mock-11-alianca",
    nome: "Residencial Campo de Toscana",
    slug: "alianca-alvenaria-estrutural",
    cidade: "Vinhedo",
    estado: "SP",
    bairro: "Vinhedo (Marambaia / Campo de Toscana)",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: "construtora-alianca",
    is_published: true,
    created_at: "2024-03-11T10:00:00Z",
    updated_at: "2024-03-11T10:00:00Z",
    preco_a_partir: 1650,
    unidades_disponiveis: 30,
    descricao_curta: "Mão de obra especializada em alvenaria estrutural, blocos de concreto e lajes treliçadas.",
    descricao_longa: "A Aliança Construtora oferece fornecimento de mão de obra e empreitada global para estruturas brutas com prumo rigoroso e produtividade acelerada.",
    cover_image_url: "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Alvenaria", "Fundações", "Preparação do Solo"],
    construtoras: {
      id: "construtora-alianca",
      nome: "Aliança Estruturas Civis",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%230f172a'/><circle cx='40' cy='50' r='18' stroke='%23ea580c' stroke-width='6' fill='none'/><circle cx='60' cy='50' r='18' stroke='%23ffffff' stroke-width='6' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.5,
      count: 15,
    },
    contato: {
      whatsapp: "5511988901234",
      telefone: "(11) 4586-1100",
      email: "obras@aliancaestruturas.com.br",
      responsavel: "Eng. Emerson Prado",
      cidadeAtendimento: "Vinhedo, Valinhos e Jundiaí",
    },
    reviews: [
      {
        id: "rev-1-ali",
        author: "Tiago Cerqueira",
        role: "Construtor Parceiro",
        content: "Equipe de alvenaria muito rápida e limpa. Fecharam a laje no tempo exato estipulado.",
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 4, qualidade: 4, preco: 5 },
        date: "Há 1 mês",
      },
    ],
  },
  {
    id: "mock-12-arte",
    nome: "Residência Burle Marx Acabamentos",
    slug: "arte-acabamento-fino-interiores",
    cidade: "Santana de Parnaíba",
    estado: "SP",
    bairro: "Burle Marx (Santana de Parnaíba)",
    categoria: "residencial",
    status: "pronto_para_morar",
    construtora_id: "construtora-arte",
    is_published: true,
    created_at: "2024-03-12T10:00:00Z",
    updated_at: "2024-03-12T10:00:00Z",
    preco_a_partir: 3900,
    unidades_disponiveis: 10,
    descricao_curta: "Mestres em assentamento de grandes formatos, porcelanatos calacata, iluminação embutida e forros.",
    descricao_longa: "A Arte & Acabamento é a equipe procurada por decoradores e especificadores para etapas críticas de entrega. Cortes em meia esquadria em 45º, nichos esculpidos e pintura eletrostática de alta fidelidade.",
    cover_image_url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
    gallery_urls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["Acabamento Fino", "Projetos & Arquitetura", "Reformas & Ampliações"],
    construtoras: {
      id: "construtora-arte",
      nome: "Arte & Acabamento Fino",
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='16' fill='%2318181b'/><path d='M25 75L45 55M55 45L75 25M70 20L80 30L60 50L50 40L70 20Z' stroke='%23ea580c' stroke-width='6' stroke-linecap='round' stroke-linejoin='round' fill='none'/></svg>",
    },
    supplier_rating: {
      score: 4.9,
      count: 38,
    },
    contato: {
      whatsapp: "5511999012345",
      telefone: "(11) 4153-6677",
      email: "contato@arteacabamento.com.br",
      responsavel: "Mestre Gilberto Salles",
      cidadeAtendimento: "Santana de Parnaíba e Barueri",
    },
    reviews: [
      {
        id: "rev-1-art",
        author: "Helena S. Meirelles",
        role: "Proprietária - Burle Marx",
        content: "O porcelanato de 1,20x1,20m ficou absolutamente perfeito, sem nenhum dente de nivelamento. Serviço impecável.",
        rating: 5,
        ratings: { tempo_execucao: 4, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 3 semanas",
      },
    ],
  },
]

const FORNECEDORES_45_AREAS: ObraWithConstrutora[] = AREAS_OBRA.map((area, idx) => {
  const cidades = ["Barueri", "Santana de Parnaíba", "Itupeva", "Campinas", "Sorocaba", "São Paulo"]
  const cidade = cidades[idx % cidades.length]
  const score = Number((4.7 + (idx % 4) * 0.1).toFixed(1))

  return {
    id: `mock-area-${area.id}`,
    nome: `${area.label} de Alto Padrão`,
    slug: `especialista-${area.id.replace(/_/g, "-")}`,
    cidade,
    estado: "SP",
    bairro: "Alphaville e Condomínios Fechados",
    categoria: "residencial",
    status: "em_obras",
    construtora_id: `construtora-${area.id}`,
    is_published: true,
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-01T10:00:00Z",
    preco_a_partir: area.benchmarkPrecoM2,
    unidades_disponiveis: 10 + (idx % 15),
    descricao_curta: area.descricao,
    descricao_longa: `${area.descricao}\n\nEspecialistas credenciados com ampla experiência em execução técnica, homologados para condomínios de alto padrão com suporte integral a projetos e ART.`,
    cover_image_url: area.imageUrl,
    gallery_urls: [area.imageUrl],
    tags: [area.label, ...area.tags, area.grupo],
    construtoras: {
      id: `construtora-${area.id}`,
      nome: `${area.label} Engenharia & Execução`,
      logo_url: "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' fill='%2318181b'/><path d='M25 75L50 25L75 75Z' stroke='%23ea580c' stroke-width='6' fill='none'/></svg>",
    },
    supplier_rating: {
      score,
      count: 20 + (idx % 30),
    },
    contato: {
      whatsapp: "5511998765432",
      telefone: "(11) 4002-8922",
      email: `contato@${area.id}.eng.br`,
      responsavel: `Engenheiro Responsável (${area.label})`,
      cidadeAtendimento: `${cidade} e Região Metropolitana`,
    },
    reviews: [
      {
        id: `rev-${area.id}`,
        author: "Cliente Verificado",
        role: "Proprietário Residencial",
        content: `Execução excelente da etapa de ${area.label}. Cumprimento de cronograma e acabamento impecável.`,
        rating: 5,
        ratings: { tempo_execucao: 5, experiencia: 5, qualidade: 5, preco: 4 },
        date: "Há 1 mês",
      },
    ],
  }
})

export const FORNECEDORES_EMULADOS: ObraWithConstrutora[] = [
  ...FORNECEDORES_BASE,
  ...FORNECEDORES_45_AREAS,
]
